### ISSUE TITLE
RuntimeError: No method found in ABI: transfer

### ISSUE THREAD

**Issue by marknguyen85** [izetex/web3-eth#15]
I'm try get data to send erc20 token to address ether and my code here

```
web3 = Web3::Eth::Rpc.new host: 'ropsten.infura.io', 
                                port: 443,  
                                connect_options: {
                                    open_timeout: 20,
                                    read_timeout: 140,
                                    use_ssl: true,
                                    rpc_path: '/xxxxxxxxxx'
                                }
ERC_ABI = [{.....}]
contractAddr = "0xFf............"
contract = web3.eth.contract(ERC_ABI).at(contractAddr)
data = contract.transfer.getData('0xg.......', 10000, {from: '0xc........'})
```

then get error 

```
RuntimeError: No method found in ABI: transfer
        from (irb):24
```

pls help me, thanks all

**Comment by marknguyen85** [comment]
I found the cause of the error, Abi must be formatted string instead of array
ex
Abi = []

format to => Abi = '[]'

**Comment by 5hanth** [comment]
`contract_instance.transfer.getData('0xEBD44a33C59612574834c84983da3FFd12D2eb37', 10).encodeABI()` 

`RuntimeError: Function transfer is not constant: transfer, requires to sign transaction`

is this right method to get encodedABI.

**Comment by noydarly** [comment]
Hi marknguyen85.
I have same issues.
i fixed abi format as yours.
but i get new issue like 5hanth.
RuntimeError: Function transfer is not constant: transfer, requires to sign transaction.
Can you help me 
best regards.

**Comment by 5hanth** [comment]
@noydarly apparently I end up using  [Ethereum.rb](https://github.com/EthWorks/ethereum.rb)

**Comment by noydarly** [comment]
Hi 5hanth
thanks for your response.
Could you tell me in detail about this?
For example...
thanks
