### ISSUE TITLE
Getting Contract Instance

### ISSUE THREAD

**Issue by woniesong92** [izetex/web3-eth#6]
I am having some trouble trying to get a contract instance and call its methods from Rails. I am using truffle, web3-eth, and Rails 5.0+.

I deployed my contract to ropsten and got the abi. The abi looks like this:

```
abi = [
  {
    "constant": false,
    "inputs": [
      {
        "name": "_to",
        "type": "address"
      },
      {
        "name": "_tokenId",
        "type": "uint256"
      }
    ],
    "name": "approve",
    "outputs": [],
    "payable": false,
    "stateMutability": "nonpayable",
    "type": "function"
  },
  ...
]
```

I first tried using this like this:

```
    web3 = Web3::Eth::Rpc.new host: 'localhost',
                              port: 9545,
                              connect_options: {
                                use_ssl: false,
                                read_timeout: 120
                              }

    abi = [...]
    @contract = web3.eth.contract(abi);
    @contract_instance = @contract.at(CONTRACT_ADDRESS)
```

But I kept getting the exception `RuntimeError: No method found in ABI`.
So I looked at how a contract instance is initialized, I noticed you're expecting `abi` to be a single element rather than an array of objects.

Is there anything I'm misunderstanding?

**Comment by woniesong92** [comment]
Ah.. I solved it. If you use the `abi` as it's usually given, Ruby stores the json objects using `symbol` as keys. The solution was to use `HashWithIndifferentAccess` for each object inside the abi.

```
abi = abi.map { |el| el.with_indifferent_access }
@contract = web3.eth.contract(abi);
@contract_instance = @contract.at(CONTRACT_ADDRESS)
@contract_instance.totalSupply
```

Do you want me to update README?

**Comment by astudnev** [comment]
You also can pass just JSON as string
