### ISSUE TITLE
Probably ABI is not related to call

### ISSUE THREAD

**Issue by IlyaDonskikh** [izetex/web3-eth#9]
When i am trying `.parse_call_args` for transaction [0x37b0e2e0...](https://rinkeby.etherscan.io/tx/0x37b0e2e0b35601b95c2f37cfdbd77b2a4a2c7b5df8ff0284cfcb9122edbb23d0) all going well. But it doesn't work for transaction [0xe0a8cf7cd1c...](https://rinkeby.etherscan.io/tx/0xe0a8cf7cd1cd61b377966b77db960647c61af524fce77973ea79cc6aed32e12f) which one provided by the same contract.

ABI: https://gist.github.com/IlyaDonskikh/dce68abcd26a4c06d2eb6e688b7bba1a (also trying to use: https://github.com/danfinlay/human-standard-token-abi/blob/master/index.js)
Error: `RuntimeError: No function found by hash , probably ABI is not related to call`
Gem: `web3-eth (0.2.13)`

**Comment by izetex** [comment]
The second transaction is not a method call. You can use method method_hash of transaction to check that it returns nil

**Comment by IlyaDonskikh** [comment]
Thanks. Now i see. My bad.
